### ISSUE TITLE
Add comments and proper line breaks in front end code

### ISSUE THREAD

**Issue by Ayush-projects** [Ayush-projects/chords#29]

**Comment by MukulKolpe** [comment]
Hey @Ayush-projects, May I take this issue??? writing comments and line breaks seems a good way to start with..

**Comment by Ayush-projects** [comment]
Sure, I guess more no of contributors are needed for this issue, anyways go on. Try to finish it before 2 days.

**Comment by MukulKolpe** [comment]
Ok, Thanks!!!

**Comment by MukulKolpe** [comment]
Yes, I think you can break this issue into two parts as adding line breaks, comments, and documentation about the front-end browser so that others may also get to work on it. @Ayush-projects

**Comment by Ayush-projects** [comment]
Done !!!

**Comment by MukulKolpe** [comment]
Ok, Great!!

**Comment by richakumari19** [comment]
I am participant in GSSOC'21. Can you please assign this to me?

**Comment by snehasana** [comment]
hey @Ayush-projects  i m a partcipant of GSSOC'21 ,as this is my first time for contributing in open source . Can I start from this issue as I can see this issue is still not closed?
